//true imports
// import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:tripper_web/surveyinvitepage.dart';
// import 'package:http/http.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart';
//import 'send_survey_page.dart'; //import send survey page

/*
// after your imports
import 'widgets/chat_view.dart';
*/

import 'package:firebase_auth/firebase_auth.dart'; // for anonymous auth/login

//init app, start
// void main() {
//   runApp(const MyApp());
// }
void main() async {

  // Initialize Firebase
  // This is required to ensure that Firebase is initialized before the app runs.
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print('Firebase initialized successfully');

  // Ensure the user is logged in anon or not
  _ensureLoggedIn();
  print('User logged in successfully');

  // Run the app
  runApp(const MyApp());
  print('App started successfully');
}

// This function checks if the user is logged in, and if not, signs them in anonymously
void _ensureLoggedIn() async {
  final auth = FirebaseAuth.instance;

  if (auth.currentUser == null) {
    await auth.signInAnonymously();
    print('[Auth] Signed in anonymously as ${auth.currentUser?.uid}');
  } else {
    print('[Auth] Already signed in: ${auth.currentUser?.uid}');
  }
}

// init browser app
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(

      //title of tab
      title: 'Demo - TripCliques',
      theme: ThemeData(

        // This is the theme of your application.
        colorScheme: ColorScheme.fromSeed(seedColor: const Color.fromARGB(136, 79, 97, 255)),
      ),

      //set title of appbar in homepage
      home: const MyHomePage(title: 'TripCliques Home Page'),
    );
  }
}

//This widget is the home page of your application. Fields in a Widget subclass are
  // always marked "final".
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

// this class extends homepage
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0; //temp counter
  int _selectedIndex = 0; //tracks tab selected

  // Define pages for each tab, EACH PAGE IS A WIDGET, index must match the tab index
  // This is a list of widgets that will be displayed in the body of the Scaffold.
  List<Widget> get _pages => [
    Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text("test 1, homepage with showcase"),
      ],
    ),
/*
    // chat widget! (PAGE 2)
    const ChatView(), 
*/
    //page 2 for flights/hotels booking
    Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text("page 2 page g"),

      ],
    ),    

    //page 3 for flights/hotels booking
    Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text("page 3 page for flights/hotels booking"),
      ],
    ),
    

    //page 4 for 
    Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text("page 4"),
      ],
    ),

    /*// page 5 for inviting friends to join your trip
    const SendSurveyPage(), // This is the page for sending survey invites
    Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text("page 5 for inviting friends to join your trip"),
      ],
    ),
    */
  ];

  // Function to handle tab changes
  void _onTabTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

 // This method is rerun every time setState is called, for instance as done   
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(

        //color of appbar
        backgroundColor: const Color.fromARGB(255, 0, 44, 189), //Theme.of(context).colorScheme.inversePrimary,
        
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),

      //body:Center(child: _pages[_selectedIndex]), // Display the selected page
      body: SizedBox.expand(child: _pages[_selectedIndex]),


      // bottom navigation bar with tabs
      // The BottomNavigationBar widget is used to create a bottom navigation bar.
      bottomNavigationBar: BottomNavigationBar(
        // colors for bottom navigation bar
        selectedItemColor: const Color.fromARGB(255, 208, 212, 255),
        backgroundColor: const Color.fromARGB(255, 0, 119, 254), //Theme.of(context).colorScheme.inversePrimary,
        type: BottomNavigationBarType.fixed, // Use fixed type for multiple items
        items: const [

          BottomNavigationBarItem(
            icon: Icon(Icons.local_fire_department),
            label: 'discover/popular destinations', //put world map and points or something, have search bar with dates,locatin, prices
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.star),
            label: 'get started', /// move the plus button from home screen to here later, that will be invite friends
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.group),
            label: 'my group', // shows the travel group you are in, with ability to add and remove members, status of survey completion
                                //has info on who has completed the survey and who has not, and ability to send reminders, also member role
                                      // also shows trip preferences like dates
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.bookmark_add), // this will be a list of history or saved trips, with ability to edit and delete
            label: 'saved trips',
          ),
        ],
        currentIndex: _selectedIndex,
        onTap: _onTabTapped, // Handle tab changes
      ),

      //function for floating action button
      // This button will only appear on the first tab (Home)
      floatingActionButton: _selectedIndex == 2 //index is which page counter is on
          ? FloatingActionButton(
              onPressed: () {
                showDialog(context: context, builder: (context) => const SurveyInviteDialog(),
                 ); // Increment the counter when the FAB is pressed
              },
              tooltip: 'Send Survey Invite',
              child: const Icon(Icons.email),
            )
          : null,
    );

    
      ////////////////
      //   // Center is a layout widget. It takes a single child and positions it in the 
      // //middle of the parent.
      // body: Column(
      //   mainAxisAlignment:MainAxisAlignment.center, 
      //   children: [
          
      //     Text("item 1"),
      //     Text("item 2"),
      //     Text("item 3"),
      //     Text('$_counter'),
      //     //ChatView(), //cannot be in lcolumn or row

      //   ],
      // ),

      ////////////
            

      ///////////////////////////// 
    

      // // button to increment count
      // floatingActionButton: FloatingActionButton(
      //   onPressed: _incrementCounter,
      //   tooltip: 'Increment',
      //   child: const Icon(Icons.add),
      // ), 

    
  }
}

